import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query'
import {
  Alert, AppBar, Box, Breadcrumbs, Button, CircularProgress, Container, CssBaseline, Dialog, DialogActions,
  DialogContent, DialogTitle, IconButton, LinearProgress, List, ListItem, ListItemButton, ListItemIcon,
  ListItemText, Paper, Stack, Tab, Tabs, TextField, ThemeProvider, Toolbar, Typography, createTheme,
} from '@mui/material'
import { Delete, Download, Folder, InsertDriveFile, Logout, Restore, Settings } from '@mui/icons-material'
import { api, formatBytes, NodeItem, setCSRF, uploadFile } from './api'

const queryClient = new QueryClient()
const theme = createTheme({ palette: { mode: 'dark', primary: { main: '#8b5cf6' }, secondary: { main: '#22d3ee' }, background: { default: '#0b1020', paper: '#151c31' } }, shape: { borderRadius: 12 } })

function App() {
  const setup = useQuery({ queryKey: ['setup'], queryFn: () => api<{configured:boolean}>('/setup/status') })
  const session = useQuery({ queryKey: ['session'], queryFn: async () => { const value = await api<{email:string;csrf_token:string}>('/auth/session'); setCSRF(value.csrf_token); return value }, retry: false, enabled: setup.data?.configured === true })
  if (setup.isLoading) return <Centered><CircularProgress/></Centered>
  if (!setup.data?.configured) return <Setup onDone={() => { setup.refetch(); session.refetch() }}/>
  if (session.isLoading) return <Centered><CircularProgress/></Centered>
  if (!session.data) return <Login onDone={() => session.refetch()}/>
  return <Dashboard email={session.data.email} onLogout={async()=>{await api('/auth/session',{method:'DELETE'});setCSRF('');queryClient.clear();location.reload()}}/>
}

function Setup({onDone}:{onDone:()=>void}) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [secret,setSecret]=useState(''); const [uri,setURI]=useState(''); const [code,setCode]=useState(''); const [recovery,setRecovery]=useState<string[]>([]); const [error,setError]=useState('')
  const start=async()=>{try{setError('');const result=await api<{manual_secret:string;otpauth_uri:string}>('/setup',{method:'POST',body:JSON.stringify({email,password})});setSecret(result.manual_secret);setURI(result.otpauth_uri)}catch(e){setError((e as Error).message)}}
  const verify=async()=>{try{const result=await api<{csrf_token:string;recovery_codes:string[]}>('/setup/verify',{method:'POST',body:JSON.stringify({code})});setCSRF(result.csrf_token);setRecovery(result.recovery_codes)}catch(e){setError((e as Error).message)}}
  return <Centered><Paper sx={{p:4,width:'min(520px,92vw)'}}><Typography variant="h4" gutterBottom>Pentaract V2</Typography><Typography color="text.secondary" sx={{mb:3}}>Create the encrypted storage owner.</Typography>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{recovery.length>0?<Stack spacing={2}><Alert severity="warning">Save these one-time recovery codes before continuing.</Alert><Box component="pre" sx={{p:2,bgcolor:'background.default',borderRadius:2}}>{recovery.join('\n')}</Box><Button variant="contained" onClick={onDone}>I saved the codes</Button></Stack>:secret?<Stack spacing={2}><Typography>Add this secret to your authenticator:</Typography><TextField value={secret} slotProps={{input:{readOnly:true}}}/><Button href={uri}>Open authenticator URI</Button><TextField label="6-digit code" value={code} onChange={e=>setCode(e.target.value)}/><Button variant="contained" onClick={verify}>Verify TOTP</Button></Stack>:<Stack spacing={2}><TextField label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)}/><TextField label="Password (12+ characters)" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><Button variant="contained" onClick={start}>Create owner</Button></Stack>}</Paper></Centered>
}

function Login({onDone}:{onDone:()=>void}) { const [email,setEmail]=useState('');const[password,setPassword]=useState('');const[code,setCode]=useState('');const[error,setError]=useState('');const submit=async()=>{try{const result=await api<{csrf_token:string}>('/auth/login',{method:'POST',body:JSON.stringify({email,password,code})});setCSRF(result.csrf_token);onDone()}catch(e){setError((e as Error).message)}};return <Centered><Paper sx={{p:4,width:'min(440px,92vw)'}}><Typography variant="h4" gutterBottom>Welcome back</Typography>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Stack spacing={2}><TextField label="Email" value={email} onChange={e=>setEmail(e.target.value)}/><TextField label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><TextField label="TOTP or recovery code" value={code} onChange={e=>setCode(e.target.value)}/><Button variant="contained" onClick={submit}>Sign in</Button></Stack></Paper></Centered> }

function Dashboard({email,onLogout}:{email:string;onLogout:()=>void}) { const[tab,setTab]=useState(0);return <><AppBar position="static" color="transparent" elevation={0}><Toolbar><Typography variant="h6" sx={{flexGrow:1}}>Pentaract V2</Typography><Typography color="text.secondary" sx={{mr:2}}>{email}</Typography><IconButton onClick={onLogout}><Logout/></IconButton></Toolbar></AppBar><Container maxWidth="lg" sx={{py:3}}><Tabs value={tab} onChange={(_,v)=>setTab(v)} sx={{mb:3}}><Tab label="Files"/><Tab label="Trash"/><Tab icon={<Settings/>} iconPosition="start" label="Settings"/></Tabs>{tab===0&&<Files/>}{tab===1&&<Trash/>}{tab===2&&<TelegramSettings/>}</Container></> }

function Files(){const[parents,setParents]=useState<{id:string|null;name:string}[]>([{id:null,name:'Home'}]);const parent=parents.at(-1)!;const[search,setSearch]=useState('');const[uploadProgress,setUploadProgress]=useState<Record<string,number>>({});const[error,setError]=useState('');const key=['files',parent.id,search];const listing=useQuery({queryKey:key,queryFn:()=>api<{items:NodeItem[]}>(`/files?${search?`q=${encodeURIComponent(search)}`:parent.id?`parent_id=${parent.id}`:''}`),refetchInterval:2000});const createFolder=async()=>{const name=prompt('Folder name');if(!name)return;await api('/folders',{method:'POST',body:JSON.stringify({name,parent_id:parent.id})});listing.refetch()};const upload=async(files:FileList|null)=>{for(const file of Array.from(files??[])){try{setUploadProgress(v=>({...v,[file.name]:0}));await uploadFile(file,parent.id,p=>setUploadProgress(v=>({...v,[file.name]:p})));setUploadProgress(v=>{const next={...v};delete next[file.name];return next});listing.refetch()}catch(e){setError((e as Error).message)}}};return <Stack spacing={2}>{error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}<Stack direction={{xs:'column',sm:'row'}} spacing={2}><TextField size="small" label="Search" value={search} onChange={e=>setSearch(e.target.value)} sx={{flexGrow:1}}/><Button variant="outlined" onClick={createFolder}>New folder</Button><Button variant="contained" component="label">Upload<input hidden multiple type="file" onChange={e=>upload(e.target.files)}/></Button></Stack><Breadcrumbs>{parents.map((p,i)=><Button key={p.id??'root'} size="small" onClick={()=>setParents(v=>v.slice(0,i+1))}>{p.name}</Button>)}</Breadcrumbs>{Object.entries(uploadProgress).map(([name,value])=><Box key={name}><Typography variant="caption">{name}</Typography><LinearProgress variant="determinate" value={value*100}/></Box>)}<Paper><List>{listing.data?.items.length?listing.data.items.map(item=><NodeRow key={item.id} item={item} open={()=>item.kind==='folder'&&setParents(v=>[...v,{id:item.id,name:item.name}])} refresh={()=>listing.refetch()}/>):<ListItem><ListItemText primary="This folder is empty"/></ListItem>}</List></Paper></Stack>}

function NodeRow({item,open,refresh}:{item:NodeItem;open:()=>void;refresh:()=>void}){const rename=async()=>{const name=prompt('New name',item.name);if(name){await api(`/files/${item.id}`,{method:'PATCH',body:JSON.stringify({name})});refresh()}};const remove=async()=>{if(confirm(`Move ${item.name} to trash?`)){await api(`/files/${item.id}`,{method:'DELETE'});refresh()}};return <ListItem secondaryAction={<Stack direction="row">{item.kind==='file'&&item.state==='ready'&&<IconButton component="a" href={`/api/v1/files/${item.id}/download`}><Download/></IconButton>}<IconButton onClick={remove}><Delete/></IconButton></Stack>} disablePadding><ListItemButton onClick={item.kind==='folder'?open:rename}><ListItemIcon>{item.kind==='folder'?<Folder color="primary"/>:<InsertDriveFile/>}</ListItemIcon><ListItemText primary={item.name} secondary={`${formatBytes(item.size)}${item.state?` · ${item.state}`:''}${item.error?` · ${item.error}`:''}`}/></ListItemButton></ListItem>}

function Trash(){const listing=useQuery({queryKey:['trash'],queryFn:()=>api<{items:NodeItem[]}>('/trash')});const restore=async(id:string)=>{await api(`/files/${id}/restore`,{method:'POST'});listing.refetch()};return <Paper><List>{listing.data?.items.map(item=><ListItem key={item.id} secondaryAction={<IconButton onClick={()=>restore(item.id)}><Restore/></IconButton>}><ListItemIcon>{item.kind==='folder'?<Folder/>:<InsertDriveFile/>}</ListItemIcon><ListItemText primary={item.name} secondary={item.purge_after?`Purges ${new Date(item.purge_after).toLocaleString()}`:''}/></ListItem>)}</List></Paper>}

function TelegramSettings(){const settings=useQuery({queryKey:['telegram-settings'],queryFn:()=>api<Record<string,unknown>>('/settings/telegram')});const[name,setName]=useState('Personal storage');const[chatID,setChatID]=useState('');const[token,setToken]=useState('');const[logout,setLogout]=useState(false);const[message,setMessage]=useState('');const save=async()=>{try{await api('/settings/telegram',{method:'PUT',body:JSON.stringify({storage_name:name,chat_id:Number(chatID),bot_token:token,logout_cloud:logout})});setToken('');setMessage('Telegram storage verified and saved');settings.refetch()}catch(e){setMessage((e as Error).message)}};return <Stack spacing={3}><Alert severity={settings.data?.configured?'success':'warning'}>{settings.data?.configured?`Connected to @${settings.data.bot_username}`:'Telegram storage is not configured'}</Alert><Paper sx={{p:3}}><Stack spacing={2}><TextField label="Storage name" value={name} onChange={e=>setName(e.target.value)}/><TextField label="Channel chat ID (-100...)" value={chatID} onChange={e=>setChatID(e.target.value)}/><TextField label="Bot token" type="password" value={token} onChange={e=>setToken(e.target.value)}/><Alert severity="info">Cloud logOut is only needed when moving this bot from the cloud Bot API to a local server. Leave it off when the bot already uses a local server. File transfers use the local server and do not require api.telegram.org.</Alert><Button variant={logout?'contained':'outlined'} onClick={()=>setLogout(v=>!v)}>Cloud logOut before local connection: {logout?'yes':'no'}</Button><Button variant="contained" onClick={save}>Verify and save</Button>{message&&<Alert severity={message.includes('saved')?'success':'error'}>{message}</Alert>}</Stack></Paper></Stack>}

function Centered({children}:{children:React.ReactNode}){return <Box sx={{minHeight:'100vh',display:'grid',placeItems:'center',p:2}}>{children}</Box>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><ThemeProvider theme={theme}><CssBaseline/><QueryClientProvider client={queryClient}><App/></QueryClientProvider></ThemeProvider></React.StrictMode>)

