import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query'
import { Add, ArrowForwardIos, CloudUpload, DeleteOutline, Download, DriveFileMoveOutlined, FolderOutlined, GridView, InfoOutlined, InsertDriveFileOutlined, Logout, Restore, Search, Settings as SettingsIcon, ShieldOutlined } from '@mui/icons-material'
import { api, formatBytes, NodeItem, progressPercent, setCSRF, uploadFile } from './api'
import './styles.css'

const queryClient = new QueryClient()

type Session = { email: string; csrf_token: string }
type TelegramConfig = { configured: boolean; storage_name?: string; chat_id?: number; bot_username?: string }

function Brand() { return <span className="brand"><span className="brand-mark">P</span><span className="brand-name">Pentaract</span></span> }
function Intro({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}) { return <div className="page-intro"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p className="lead">{description}</p></div>{action}</div> }
function Feedback({children,onClose}:{children:React.ReactNode;onClose?:()=>void}) { return <div className="notice" role="alert"><InfoOutlined/><div><span>{children}</span></div>{onClose&&<button type="button" className="icon-btn" onClick={onClose} aria-label="Закрыть">×</button>}</div> }
function Empty({title,description,action}:{title:string;description:string;action?:React.ReactNode}) { return <div className="empty"><span className="empty-symbol"><FolderOutlined/></span><h2>{title}</h2><p>{description}</p>{action}</div> }
function DialogShell({title,children,onClose,onSubmit,submitLabel,disabled=false}:{title:string;children:React.ReactNode;onClose:()=>void;onSubmit:(e:React.FormEvent)=>void;submitLabel:string;disabled?:boolean}) { return <div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="dialog" role="dialog" aria-modal="true" aria-label={title}><div className="dialog-head"><h2>{title}</h2><button type="button" className="icon-btn" onClick={onClose} aria-label="Закрыть">×</button></div><form onSubmit={onSubmit}>{children}<div className="dialog-actions"><button className="btn" type="button" onClick={onClose}>Отмена</button><button className="btn btn-primary" type="submit" disabled={disabled}>{submitLabel}</button></div></form></div></div> }

function App() {
  const setup = useQuery({queryKey:['setup'],queryFn:()=>api<{configured:boolean}>('/setup/status')})
  const session = useQuery({queryKey:['session'],queryFn:async()=>{const value=await api<Session>('/auth/session');setCSRF(value.csrf_token);return value},retry:false,enabled:setup.data?.configured===true})
  if(setup.isLoading||session.isLoading) return <div className="loading">Загрузка Pentaract…</div>
  if(setup.isError) return <div className="loading" role="alert">Не удалось проверить настройки приложения.</div>
  if(!setup.data?.configured) return <Setup onDone={()=>{setup.refetch();session.refetch()}}/>
  if(!session.data) return <Login onDone={()=>session.refetch()}/>
  return <Dashboard email={session.data.email} onLogout={async()=>{await api('/auth/session',{method:'DELETE'});setCSRF('');queryClient.clear();location.reload()}}/>
}

function Setup({onDone}:{onDone:()=>void}) {
  const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[secret,setSecret]=useState('');const[uri,setURI]=useState('');const[code,setCode]=useState('');const[recovery,setRecovery]=useState<string[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState(false)
  const start=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{setError('');const result=await api<{manual_secret:string;otpauth_uri:string}>('/setup',{method:'POST',body:JSON.stringify({email,password})});setSecret(result.manual_secret);setURI(result.otpauth_uri)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const verify=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{setError('');const result=await api<{csrf_token:string;recovery_codes:string[]}>('/setup/verify',{method:'POST',body:JSON.stringify({code})});setCSRF(result.csrf_token);setRecovery(result.recovery_codes)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="login-shell"><aside className="login-story"><Brand/><div className="login-copy"><span className="eyebrow">Личное хранилище</span><h1>Ваши файлы.<br/>Ваш порядок.</h1><p>Спокойное пространство для файлов, папок и понятного контроля загрузки.</p></div></aside><main className="login-form-side"><div className="login-card"><span className="eyebrow">Первый запуск</span><h2>Настройка Pentaract</h2><p className="lead">Создайте владельца хранилища и включите двухфакторную защиту.</p>{error&&<div className="login-summary" role="alert">{error}</div>}{recovery.length>0?<div className="login-form"><Feedback>Сохраните одноразовые коды восстановления перед продолжением.</Feedback><pre className="recovery-codes">{recovery.join('\n')}</pre><button className="btn btn-primary" onClick={onDone}>Я сохранил коды</button></div>:secret?<form className="login-form" onSubmit={verify}><label className="field-label" htmlFor="setup-secret">Секрет для приложения аутентификации</label><input className="field" id="setup-secret" value={secret} readOnly/><a className="btn" href={uri}>Открыть в приложении</a><label className="field-label" htmlFor="setup-code">Шестизначный код</label><input className="field" id="setup-code" value={code} onChange={e=>setCode(e.target.value)} required/><button className="btn btn-primary" disabled={busy}>Проверить TOTP</button></form>:<form className="login-form" onSubmit={start}><label className="field-label" htmlFor="setup-email">Email</label><input className="field" id="setup-email" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/><label className="field-label" htmlFor="setup-password">Пароль (от 12 символов)</label><input className="field" id="setup-password" type="password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} required/><button className="btn btn-primary" disabled={busy}>Создать владельца</button></form>}</div></main></div>
}

function Login({onDone}:{onDone:()=>void}) {
  const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[code,setCode]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false)
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{setError('');const result=await api<{csrf_token:string}>('/auth/login',{method:'POST',body:JSON.stringify({email,password,code})});setCSRF(result.csrf_token);onDone()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="login-shell"><aside className="login-story"><Brand/><div className="login-copy"><span className="eyebrow">Личное хранилище</span><h1>Ваши файлы.<br/>Ваш порядок.</h1><p>Спокойное пространство для файлов, папок и понятного контроля загрузки.</p></div><div className="login-steps"><div className="login-step"><span className="login-step-number">01</span>Откройте личное пространство</div><div className="login-step"><span className="login-step-number">02</span>Найдите нужный файл или загрузите новый</div><div className="login-step"><span className="login-step-number">03</span>Следите за этапами отправки</div></div></aside><main className="login-form-side"><div className="login-card"><span className="eyebrow">С возвращением</span><h2>Вход в Pentaract</h2><p className="lead">Введите данные своей учётной записи.</p><form className="login-form" onSubmit={submit}>{error&&<div className="login-summary" role="alert">{error}</div>}<div className="login-field"><label className="field-label" htmlFor="login-email">Email</label><input className="field" id="login-email" type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="login-field"><label className="field-label" htmlFor="login-password">Пароль</label><input className="field" id="login-password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><div className="login-field"><label className="field-label" htmlFor="login-code">Код TOTP или восстановления</label><input className="field" id="login-code" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)} required/></div><button className="btn btn-primary login-submit" type="submit" disabled={busy}>{busy?'Входим…':'Войти'} <ArrowForwardIos/></button></form></div></main></div>
}

function Dashboard({email,onLogout}:{email:string;onLogout:()=>void}) {
  const[tab,setTab]=useState<'files'|'trash'|'settings'>('files');const[logoutError,setLogoutError]=useState('')
  const logout=async()=>{try{await onLogout()}catch(e){setLogoutError((e as Error).message)}}
  return <div className="app"><aside className="sidebar"><Brand/><div className="mobile-brand"><span className="brand-mark">P</span>Pentaract</div><span className="nav-label">Хранилище</span><nav className="nav" aria-label="Основная навигация"><button aria-current={tab==='files'?'page':undefined} onClick={()=>setTab('files')}><GridView/>Файлы</button><button aria-current={tab==='trash'?'page':undefined} onClick={()=>setTab('trash')}><DeleteOutline/>Корзина</button><button aria-current={tab==='settings'?'page':undefined} onClick={()=>setTab('settings')}><SettingsIcon/>Настройки</button></nav><div className="sidebar-foot"><strong>Личное пространство</strong><span>Ваши файлы и папки.</span></div></aside><main className="main"><div className="page"><header className="topbar"><span className="topbar-label">Pentaract</span><span className="topbar-user"><span>{email}</span><span className="avatar" aria-hidden="true">{email.slice(0,2).toUpperCase()}</span><button className="logout-btn" onClick={logout} aria-label="Выйти"><Logout/>Выйти</button></span></header>{logoutError&&<Feedback>{logoutError}</Feedback>}</div>{tab==='files'?<Files/>:tab==='trash'?<Trash/>:<TelegramSettings/>}</main></div>
}

function Files(){
  const[parents,setParents]=useState<{id:string|null;name:string}[]>([{id:null,name:'Файлы'}]);const parent=parents.at(-1)!;const[search,setSearch]=useState('');const[uploadProgress,setUploadProgress]=useState<Record<string,number>>({});const[error,setError]=useState('');const[folderOpen,setFolderOpen]=useState(false);const[folderName,setFolderName]=useState('');const[busy,setBusy]=useState(false)
  const listing=useQuery({queryKey:['files',parent.id,search],queryFn:()=>api<{items:NodeItem[]}>(`/files?${search?`q=${encodeURIComponent(search)}`:parent.id?`parent_id=${encodeURIComponent(parent.id)}`:''}`),refetchInterval:2000})
  const createFolder=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api('/folders',{method:'POST',body:JSON.stringify({name:folderName,parent_id:parent.id})});setFolderOpen(false);setFolderName('');listing.refetch()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const upload=async(files:FileList|null)=>{for(const file of Array.from(files??[])){try{setUploadProgress(v=>({...v,[file.name]:0}));await uploadFile(file,parent.id,p=>setUploadProgress(v=>({...v,[file.name]:p})));listing.refetch()}catch(e){setError((e as Error).message)}finally{setUploadProgress(v=>{const next={...v};delete next[file.name];return next})}}}
  const picker=<input className="file-picker" aria-label="Выбрать файлы" type="file" multiple onChange={e=>{upload(e.target.files);e.target.value=''}}/>
  return <section className="page"><Intro eyebrow="Личное пространство" title={parent.name} description="Ваши файлы и папки в одном спокойном рабочем пространстве." action={<label className="btn btn-primary upload-label"><CloudUpload/>Загрузить файлы{picker}</label>}/>{error&&<Feedback onClose={()=>setError('')}>{error}</Feedback>}<div className="toolbar"><label className="search"><Search/><input className="field" type="search" placeholder="Поиск по имени" aria-label="Поиск файлов" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="btn" onClick={()=>setFolderOpen(true)}><Add/>Новая папка</button></div><nav className="breadcrumbs" aria-label="Путь к папке">{search?'Результаты поиска':parents.map((p,i)=><React.Fragment key={p.id??'root'}>{i>0&&<ArrowForwardIos/>}<button className="crumb" aria-current={i===parents.length-1?'page':undefined} onClick={()=>setParents(v=>v.slice(0,i+1))}>{p.name}</button></React.Fragment>)}</nav>{Object.entries(uploadProgress).map(([name,value])=><div className="upload-progress" key={name}><span>Загрузка на этот Mac: {name} · {Math.floor(value*100)}%</span><div className="progress"><span style={{width:`${value*100}%`}}/></div></div>)}<div className="panel"><div className="panel-head"><span className="panel-title">{search?'Найденные элементы':'Содержимое папки'}</span><span className="panel-subtitle">{listing.data?.items.length??0} элементов</span></div>{listing.isError?<Empty title="Не удалось загрузить файлы" description={(listing.error as Error).message}/>:listing.isLoading?<div className="empty">Загрузка…</div>:listing.data?.items.length?<div className="file-list">{listing.data.items.map(item=><NodeRow key={item.id} item={item} open={()=>item.kind==='folder'&&setParents(v=>[...v,{id:item.id,name:item.name}])} refresh={()=>listing.refetch()}/>)}</div>:<Empty title={search?'Ничего не найдено':'Папка пуста'} description={search?'Попробуйте другое название или очистите поиск.':'Загрузите файл или создайте новую папку.'} action={search?<button className="btn" onClick={()=>setSearch('')}>Очистить поиск</button>:<label className="btn btn-primary upload-label">Загрузить файлы{picker}</label>}/>}</div>{folderOpen&&<DialogShell title="Новая папка" onClose={()=>setFolderOpen(false)} onSubmit={createFolder} submitLabel="Создать" disabled={busy}><label className="field-label" htmlFor="folder-name">Название</label><input autoFocus className="field" id="folder-name" value={folderName} onChange={e=>setFolderName(e.target.value)} required maxLength={100}/></DialogShell>}</section>
}

function NodeRow({item,open,refresh}:{item:NodeItem;open:()=>void;refresh:()=>void}){
  const[moveOpen,setMoveOpen]=useState(false);const[renameOpen,setRenameOpen]=useState(false);const[name,setName]=useState(item.name);const[error,setError]=useState('');const[busy,setBusy]=useState(false)
  const run=async(action:()=>Promise<unknown>)=>{setBusy(true);try{setError('');await action();refresh();return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
  const rename=async(e:React.FormEvent)=>{e.preventDefault();if(await run(()=>api(`/files/${item.id}`,{method:'PATCH',body:JSON.stringify({name})})))setRenameOpen(false)}
  const remove=()=>{if(confirm(`Переместить «${item.name}» в корзину?`))run(()=>api(`/files/${item.id}`,{method:'DELETE'}))}
  const active=item.state==='uploading'||item.state==='processing';const progress=item.progress_bytes??0
  const stateLabel=item.state==='uploading'?'На Mac':item.state==='processing'?'В Telegram':item.state==='queued'?'В очереди':item.state==='failed'?'Ошибка':'Готово'
  return <div className="file-row"><div className="file-main"><span className={`file-icon ${item.kind==='folder'?'folder':''}`}>{item.kind==='folder'?<FolderOutlined/>:<InsertDriveFileOutlined/>}</span><span className="file-content"><button className="file-name od-truncate" onClick={item.kind==='folder'?open:()=>setRenameOpen(true)} title={item.name}>{item.name}</button><span className="file-meta">{item.kind==='folder'?`${item.file_count??0} файлов · ${formatBytes(item.total_size??0)}`:`${formatBytes(item.size)} · ${stateLabel}`}</span>{active&&<><span className="file-meta">{item.state==='uploading'?'Загрузка на этот Mac':'Отправка в Telegram'} · {formatBytes(progress)} из {formatBytes(item.size)} · {progressPercent(progress,item.size)}%. Держите Mac включённым.</span><div className="progress"><span style={{width:`${progressPercent(progress,item.size)}%`}}/></div></>}{item.state==='queued'&&<span className="file-meta">Ожидает отправки в Telegram. Держите Mac включённым.</span>}{item.error&&<span className="field-error">{item.error}</span>}{error&&<span className="field-error">{error}</span>}</span></div><span className="file-size">{item.kind==='folder'?'—':formatBytes(item.size)}</span><span className="file-date">{new Date(item.created_at).toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}</span><div className="file-actions">{item.kind==='file'&&item.state==='ready'&&<><button className="icon-btn" title="Переместить" aria-label={`Переместить ${item.name}`} onClick={()=>setMoveOpen(true)}><DriveFileMoveOutlined/></button><a className="icon-btn" title="Скачать" aria-label={`Скачать ${item.name}`} href={`/api/v1/files/${item.id}/download`}><Download/></a></>}{item.kind==='folder'&&<button className="icon-btn" title="Переименовать" aria-label={`Переименовать ${item.name}`} onClick={()=>setRenameOpen(true)}>•••</button>}<button className="icon-btn" title="В корзину" aria-label={`В корзину ${item.name}`} onClick={remove} disabled={busy}><DeleteOutline/></button></div>{moveOpen&&<MoveFileDialog item={item} onClose={()=>setMoveOpen(false)} onMoved={()=>{setMoveOpen(false);refresh();queryClient.invalidateQueries({queryKey:['files']})}}/>}{renameOpen&&<DialogShell title="Переименовать" onClose={()=>setRenameOpen(false)} onSubmit={rename} submitLabel="Сохранить" disabled={busy}>{error&&<Feedback>{error}</Feedback>}<label className="field-label" htmlFor={`rename-${item.id}`}>Название</label><input className="field" id={`rename-${item.id}`} value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/></DialogShell>}</div>
}

function MoveFileDialog({item,onClose,onMoved}:{item:NodeItem;onClose:()=>void;onMoved:()=>void}){
  const[destination,setDestination]=useState(item.parent_id??'');const[error,setError]=useState('');const[moving,setMoving]=useState(false)
  const folders=useQuery({queryKey:['folders'],queryFn:()=>api<{items:{id:string;path:string}[]}>('/folders')})
  const move=async(e:React.FormEvent)=>{e.preventDefault();setMoving(true);setError('');try{await api(`/files/${item.id}/move`,{method:'POST',body:JSON.stringify({parent_id:destination||null})});onMoved()}catch(e){setError((e as Error).message);setMoving(false)}}
  return <DialogShell title={`Переместить «${item.name}»`} onClose={onClose} onSubmit={move} submitLabel="Переместить" disabled={folders.isLoading||folders.isError||moving||destination===(item.parent_id??'')}>{error&&<Feedback>{error}</Feedback>}{folders.isError&&<Feedback>Не удалось загрузить папки.</Feedback>}<label className="field-label" htmlFor="destination">Назначение</label><select className="field" id="destination" value={destination} onChange={e=>setDestination(e.target.value)} disabled={folders.isLoading||folders.isError||moving}><option value="">Все файлы</option>{folders.data?.items.map(folder=><option key={folder.id} value={folder.id}>{folder.path}</option>)}</select></DialogShell>
}

function Trash(){const listing=useQuery({queryKey:['trash'],queryFn:()=>api<{items:NodeItem[]}>('/trash')});const[error,setError]=useState('');const restore=async(id:string)=>{try{setError('');await api(`/files/${id}/restore`,{method:'POST'});listing.refetch();queryClient.invalidateQueries({queryKey:['files']})}catch(e){setError((e as Error).message)}};return <section className="page"><Intro eyebrow="Управление файлами" title="Корзина" description="Удалённые элементы можно восстановить."/>{error&&<Feedback>{error}</Feedback>}<div className="panel"><div className="panel-head"><span className="panel-title">Удалённые элементы</span><span className="panel-subtitle">{listing.data?.items.length??0} элементов</span></div>{listing.isError?<Empty title="Не удалось загрузить корзину" description={(listing.error as Error).message}/>:listing.isLoading?<div className="empty">Загрузка…</div>:listing.data?.items.length?listing.data.items.map(item=><div className="file-row" key={item.id}><div className="file-main"><span className={`file-icon ${item.kind==='folder'?'folder':''}`}>{item.kind==='folder'?<FolderOutlined/>:<InsertDriveFileOutlined/>}</span><span className="file-content"><strong className="file-name">{item.name}</strong><span className="file-meta">{item.purge_after?`Удалится ${new Date(item.purge_after).toLocaleString('ru-RU')}`:'Удалённый элемент'}</span></span></div><span className="file-size">{item.kind==='folder'?'—':formatBytes(item.size)}</span><span className="file-date"/><div className="file-actions"><button className="icon-btn" aria-label={`Восстановить ${item.name}`} title="Восстановить" onClick={()=>restore(item.id)}><Restore/></button></div></div>):<Empty title="Корзина пуста" description="Удалённые файлы и папки появятся здесь."/>}</div></section>}

function TelegramSettings(){
  const settings=useQuery({queryKey:['telegram-settings'],queryFn:()=>api<TelegramConfig>('/settings/telegram')});const[name,setName]=useState('');const[chatID,setChatID]=useState('');const[token,setToken]=useState('');const[logout,setLogout]=useState(false);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false)
  useEffect(()=>{if(settings.data){setName(settings.data.storage_name??'');setChatID(settings.data.chat_id?String(settings.data.chat_id):'')}},[settings.data])
  const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api('/settings/telegram',{method:'PUT',body:JSON.stringify({storage_name:name,chat_id:Number(chatID),bot_token:token,logout_cloud:logout})});setToken('');setMessage('Хранилище Telegram проверено и сохранено.');settings.refetch()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
  return <section className="page"><Intro eyebrow="Подключение" title="Настройки Telegram" description="Параметры хранилища и состояние соединения в одном месте."/>{settings.isError&&<Feedback>Не удалось загрузить настройки Telegram.</Feedback>}<div className="settings-layout"><div className="panel settings-card"><div className="settings-heading"><div><h2>Хранилище</h2><p>Укажите канал и токен бота для проверки соединения.</p></div><span className="tag">{settings.data?.configured?'ПОДКЛЮЧЕНО':'НЕ НАСТРОЕНО'}</span></div>{settings.data?.configured&&<Feedback>Подключено к @{settings.data.bot_username}</Feedback>}<form className="form-grid" onSubmit={save}><div><label className="field-label" htmlFor="storage-name">Название хранилища</label><input className="field" id="storage-name" value={name} onChange={e=>setName(e.target.value)} required/></div><div><label className="field-label" htmlFor="chat-id">ID канала</label><input className="field" id="chat-id" inputMode="numeric" placeholder="-100…" value={chatID} onChange={e=>setChatID(e.target.value)} required/><span className="form-help">Отрицательный ID канала Telegram.</span></div><div><label className="field-label" htmlFor="bot-token">Токен бота</label><input className="field" id="bot-token" type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} required/></div><label className="checkbox-row"><input type="checkbox" checked={logout} onChange={e=>setLogout(e.target.checked)}/>Завершить облачную сессию бота перед локальным подключением</label><div className="settings-actions"><button className="btn btn-primary" disabled={busy}>Проверить и сохранить</button></div>{message&&<Feedback>{message}</Feedback>}</form></div><aside className="settings-note"><ShieldOutlined/><h3>Подключение Telegram</h3><p>Параметры проверяются приложением при сохранении. Токен не отображается после отправки.</p></aside></div></section>
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={queryClient}><App/></QueryClientProvider></React.StrictMode>)
